name: "maths"

description: "operations"

inputs:
  operation-A:
    description: "valor1"
    required: true
    default:

  operation-B:
    description: "valor2"
    required: true
    default: 

  operation:
    description: "resultado_total"
    required: true

outputs:
  result:
    description: "result"   

runs:
  using: "composite"
  steps:
    - run: |
         if [ operation=="suma" ] then
          result=valor1 + valor2
         elif [ operation=="multiplicacion" ] then
           result=valor2 * resultado_total
         else
           echo operation error  exit-1
         fi
         result=0
         echo result=$result >> $GITHUB_ENV
         echo "Mi resultado es: $result"
         
      shell: bash
 
      
