name: "maths"

description: "operations"

inputs:
  operation-A:
    description: "valor1"
    required: true
    
  operation-B:
    description: "valor2"
    required: true

  operation:
    description: "operacion "
    required: true

outputs:
  result:
    description: "result"   

runs:
  using: "composite"
  steps:
    - run: |
       result=0
       if [ "${{ inputs.operation }}" == "suma" ]; then
          result=${{ inputs.operation-A }}+${{ inputs.operation-B}}
          echo "sum of two numbers"
       elif [ "${{ inputs.operation }}" == "multiplicacion" ]; then
          result=${{ inputs.operation-A }}*${{ inputs.operation-B}}
       elif [ "${{ inputs.operation }}" == "resta" ]; then
          result=${{ inputs.operation-A }}-${{ inputs.operation-B}}
       elif [ "${{ inputs.operation }}" == "division" ]; then
          result=${{ inputs.operation-A }}/${{ inputs.operation-B}}
       else
          echo "error la operacion no existe!"
          exit 1
       fi
       
       echo result=$((result)) >> $GITHUB_ENV
       echo "Mi resultado es $((result))"
         
      shell: bash
