name: "maths"

description: "operations"

inputs:
  operation-A:
    description: "valor1"
    required: true
    default:

  operation-B:
    description: "valor2"
    required: true
    default: 

  operation:
    description: "resultado_total"
    required: true

outputs:
  result:
    description: "result"   

runs:
  using: "composite"
  steps:
    - run: 
       if $suma {{ inputs.valor1 }}
         result= operation-A + operation-B
          echo "sum of two numbers"
       elif $multiplicacion {{ inputs.valor2 }}
         result= operation-A * operation-B
       else
         echo "error exit-1"
       fi
         echo result=$result >> $GITHUB_ENV
         echo "Mi resultado es $result"
         
      shell: bash
 
