name: "maths"

description: "operations"

inputs:
  operation-A:
    description: "valor1"
    required: true
    
  operation-B:
    description: "valor2"
    required: true

  operation:
    description: "resultado_total"
    required: true

outputs:
  result:
    description: "result"   

runs:
  using: "composite"
  steps:
    - run: 
       if echo suma $[ inputs.operation == "suma" ]; then
          result=$operation-A+$operation-B
          echo "sum of two numbers"
       elif echo "::set-output [ operation == "multiplicacion" ]; then
          result=$operation-A\*$operation-B
       else
          echo "error la operacion no existe!"
          exit 1
       fi
       
       echo result=$result >> $GITHUB_ENV
       echo "Mi resultado es $result"
         
      shell: bash
 
