name: "maths"

description: "operations"

inputs:
  operation-A:
    description: "valor1"
    required: true
    default:

  operation-B:
    description: "valor2"
    required: true
    default: 

  operation:
    description: "resultado_total"
    required: true

outputs:
  result:
    description: "result"   

runs:
  using: "composite"
  steps:
    - run: |
         if [ operation-A=="suma" ] then
          result=valor1 + valor2
         elif [ operation-B=="multiplicacion" ] then
           result=valor1 * valor2
         else
           echo operation error exit code 1
         fi
         result=0
         echo result=$result >> $GITHUB_ENV
         echo "Mi resultado es: $result"
         
      shell: bash
 
      
