name: JS Actions

on: 
  push:
  pull_request:
    types: [labeled]

jobs:

  maths:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: suma
        uses: ./.github/actions/maths
        with:
          operation-A: 5
          operation-B: 55
          operation: suma
       
      - name: multiplicacion
        uses: ./.github/actions/maths
        with:
          operation-A: 15
          operation-B: ${{ env.result }}
          operation: multiplicacion
